# Linear regression

In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv("mobile_train.csv")

In [4]:
dataset.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [5]:
dataset.tail()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [6]:
dataset.isnull().values.any()

False

In [7]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.2 KB

In [8]:
#our target is prediction of price range

In [9]:
target = dataset.price_range

In [10]:
#stat of the dataset

In [11]:
dataset.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [12]:
#importing libraries for data visualisation and analysis

In [13]:
import matplotlib.pyplot as plt

In [14]:
import seaborn as sb

In [15]:
%matplotlib inline

In [16]:
#how ram affected by price

In [17]:
#train_dataset = dataset.drop('price_range',axis = 1)

In [18]:
train_dataset_x = dataset.drop(['price_range','blue','mobile_wt','talk_time','wifi'],axis = 'columns')

In [19]:
#split dataset into train and testing datasets

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(train_dataset_x, target, test_size=0.33, random_state=101)

In [22]:
#model training

In [23]:
from sklearn.linear_model import LinearRegression
pred_model = LinearRegression()

In [24]:
pred_model.fit(X_train,Y_train)

LinearRegression()

In [25]:
pred_model.score(X_test,Y_test)

0.9124894707357876

In [26]:
test_dataset = pd.read_csv("mobile_test.csv")

In [27]:
test_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   battery_power  1000 non-null   int64
 2   blue           1000 non-null   int64
 3   clock_speed    1000 non-null   float64
 4   dual_sim       1000 non-null   int64
 5   fc             1000 non-null   int64
 6   four_g         1000 non-null   int64
 7   int_memory     1000 non-null   int64
 8   m_dep          1000 non-null   float64
 9   mobile_wt      1000 non-null   int64
 10  n_cores        1000 non-null   int64
 11  pc             1000 non-null   int64
 12  px_height      1000 non-null   int64
 13  px_width       1000 non-null   int64
 14  ram            1000 non-null   int64
 15  sc_h           1000 non-null   int64
 16  sc_w           1000 non-null   int64
 17  talk_time      1000 non-null   int64
 18  three_g        1000 non-null   int64
 19  touch_screen   1000 non-null   int64
 20  wifi           1000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 164.2 KB

In [28]:
predict_data = test_dataset.drop(['id','blue','mobile_wt','talk_time','wifi'],axis = 'columns')

In [29]:
predict_data.head()

,battery_power,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,three_g,touch_screen
0,1043,1.8,1,14,0,5,0.1,3,16,226,1412,3476,12,7,0,1
1,841,0.5,1,4,1,61,0.8,5,12,746,857,3895,6,0,1,0
2,1807,2.8,0,1,0,27,0.9,3,4,1270,1366,2396,17,10,0,1
3,1546,0.5,1,18,1,25,0.5,8,20,295,1752,3893,10,0,1,1
4,1434,1.4,0,11,1,49,0.5,6,18,749,810,1773,15,8,1,0

In [30]:
train_dataset_x.head()

,battery_power,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,three_g,touch_screen
0,842,2.2,0,1,0,7,0.6,2,2,20,756,2549,9,7,0,0
1,1021,0.5,1,0,1,53,0.7,3,6,905,1988,2631,17,3,1,1
2,563,0.5,1,2,1,41,0.9,5,6,1263,1716,2603,11,2,1,1
3,615,2.5,0,0,0,10,0.8,6,9,1216,1786,2769,16,8,1,0
4,1821,1.2,0,13,1,44,0.6,2,14,1208,1212,1411,8,2,1,1

In [31]:
predicted_price = pred_model.predict(predict_data)

In [32]:
predicted_price

array([ 2.56837364e+00,  2.92080256e+00,  2.27636483e+00,  3.39832945e+00,
        1.20627719e+00,  2.84022365e+00,  3.65154834e+00,  1.06208799e+00,
        2.58495262e+00, -5.27960060e-02,  3.30474413e+00,  3.27374524e+00,
       -8.54846012e-02,  4.14364829e-01,  2.07949126e+00,  3.76180038e-01,
        1.93289737e+00,  1.15385031e+00,  3.15536356e+00,  1.61864510e+00,
        7.85974178e-01,  2.46792197e+00,  1.33206468e+00,  1.31042933e+00,
        3.20609567e+00,  2.91135644e-02,  2.03569447e+00, -4.12166404e-01,
        2.61120715e+00, -3.61855971e-02,  2.17090387e+00,  2.30334124e-01,
        2.83302009e+00,  1.91364276e-01,  5.72364060e-01,  9.58373013e-01,
        2.75103876e+00,  1.14821145e+00,  2.13601110e+00,  9.14894027e-01,
        1.20067193e+00,  1.74965537e+00, -4.60356268e-01, -3.72084859e-01,
       -5.62429356e-03,  7.99233847e-01,  4.14762100e-01,  2.61296391e+00,
        1.00741565e+00,  2.12445537e+00,  1.39122570e+00, -7.48353459e-02,
        2.39660532e+00,  3.75322888e-01,  3.16202658e+00,  6.77920989e-01,
        3.08330810e+00,  1.11725200e+00,  7.41511322e-01,  3.09780993e+00,
        3.10170117e+00,  2.53586399e+00,  1.70636980e-01,  1.48332087e+00,
        6.08999150e-01,  1.00004606e+00,  1.39749793e+00,  2.46045098e+00,
        9.82648526e-01,  1.71753702e+00,  1.08573130e+00,  1.92808709e+00,
        1.98887057e+00,  3.20351917e+00,  3.15169474e+00, -1.04588624e-01,
        1.92080069e+00,  1.74806496e-01,  1.60720760e+00,  3.31068711e+00,
        4.76263056e-01,  3.09414373e+00,  3.32964618e+00,  1.06639510e-01,
        3.16754280e+00,  2.45025974e-01,  2.87172490e+00,  8.57724354e-01,
        2.44583680e+00,  4.04514951e-01,  9.43485033e-01,  1.53127090e+00,
        2.23223355e+00,  5.06106013e-01,  1.83446757e+00,  1.53317609e+00,
        5.05444082e-01,  1.65740508e+00,  1.05486865e+00,  2.26384263e+00,
        8.48246108e-01,  3.26828391e-01, -4.69015149e-01,  2.56821582e+00,
        5.16632969e-01,  2.04536982e+00,  4.20133905e-01,  8.25340289e-01,
        1.91291883e+00,  2.92744601e+00,  2.94537765e+00,  2.45900764e+00,
        1.15776280e+00,  3.42120156e+00,  2.79433523e+00,  2.90678324e+00,
        3.19494988e+00,  1.66926549e+00,  2.87162302e+00,  2.40144375e-01,
       -1.97590029e-01,  2.62276743e+00,  1.68799699e+00,  1.25226375e+00,
        1.55780952e+00,  3.27040091e-01,  3.03570712e+00,  2.20327891e+00,
        2.47090861e+00,  1.35738874e+00, -6.36732397e-01,  1.76068454e+00,
        1.46794722e+00,  9.65761004e-01,  2.63652525e+00,  8.08759501e-01,
        1.41374016e+00, -8.70805054e-02,  3.26275838e+00,  2.06593694e+00,
        1.18686800e+00,  2.30827771e+00,  1.33684283e+00,  2.26717331e+00,
        2.37597343e+00,  2.92812453e+00,  2.88385950e+00,  2.40096278e+00,
        1.85061651e+00,  3.17623214e+00,  2.26472823e+00,  2.98782019e+00,
        6.29833876e-01,  1.90582640e-01,  2.56224348e+00,  1.76756630e+00,
        3.93555673e+00,  2.78462315e+00,  2.56474457e+00,  2.92171773e+00,
        2.20414820e+00,  1.96318272e+00,  2.95734028e+00,  2.67155259e+00,
        2.90194610e+00,  2.83121057e+00,  8.09958012e-01, -2.91581480e-01,
        3.27616399e+00, -4.13033832e-01, -6.77961519e-01,  2.87575065e-01,
        1.63717328e+00,  5.62787682e-01, -3.26685635e-01,  1.38902839e+00,
        3.91544830e-01,  1.74927100e-01,  7.81320358e-01,  2.07545696e+00,
        7.37604829e-01, -4.78198085e-01,  3.46780257e-01,  6.46716764e-01,
        1.49122972e+00,  2.14013382e+00,  1.66466549e+00,  9.80841871e-01,
       -6.19680606e-02,  4.37532679e-01, -3.39890642e-01,  6.22792800e-01,
        5.08698694e-01,  3.02878614e+00,  1.28070518e+00,  5.15131056e-01,
        2.14703208e+00,  1.84955514e+00,  2.30027248e+00,  2.52316266e+00,
        8.85669118e-01,  1.53895388e+00,  2.40359896e+00,  2.32449793e+00,
        2.61080857e+00,  1.68650264e+00,  1.69358656e+00,  9.48432126e-01,
        5.78060844e-01,  4.93214959e-01,  1.04920953e+00,  2.31524266e+00,
        5.93890687e-01,  2.21819347e+00,  2.53385569e+00,  2.80353995e+00,
        1.56929204e-01,  1.91616975e+00,  4.40059336e-01,  3.02694372e+00,
        1.62065273e+00,  2.38252176e+00,  2.69611069e+00,  7.83234869e-01,
       -3.37639102e-02,  9.83968437e-01,  3.21652332e-01,  2.96918976e+00,
       -6.76580696e-02,  1.35883567e+00, -1.76719341e-01,  2.09324277e+00,
        1.81085807e+00,  1.02613647e+00,  2.32196040e+00,  5.95655469e-01,
        2.56300698e+00,  3.37860145e-02,  3.22143030e+00,  9.18197948e-01,
        2.10489482e+00, -4.45857383e-01, -3.58909452e-01,  1.96532077e+00,
        8.10786945e-01,  2.56696260e+00,  2.42495114e+00,  2.81472385e+00,
        1.14714718e+00,  1.20139433e+00,  2.87235357e+00,  1.80119015e-01,
       -6.29955814e-02,  2.12654202e+00,  2.73884162e+00,  3.00895766e+00,
        1.30658948e+00,  3.25184304e+00,  1.24203554e+00,  6.39979519e-01,
        2.69263705e+00,  1.97775764e+00,  8.89424952e-01,  1.98200183e+00,
        3.56011425e+00,  2.78136357e+00,  3.36101786e+00,  1.03462629e+00,
        3.85594500e-01,  6.78894585e-01,  1.59355996e+00,  2.56885208e+00,
        1.43857058e+00,  9.84433979e-01,  3.33683000e+00,  2.07063255e+00,
        5.16210367e-01,  2.68411153e+00,  3.40211515e-01,  6.01665032e-01,
        2.28922310e+00,  5.54801384e-01, -7.25356827e-01,  3.62584871e+00,
        2.17492201e+00,  2.77183395e+00,  2.43933381e+00,  2.11146479e+00,
        8.09539856e-01,  2.86360236e+00,  2.51810865e+00,  1.94977779e+00,
        2.99625179e+00,  1.46608168e+00,  2.16600415e+00,  8.05177656e-01,
        1.55628716e+00,  1.17474174e-01,  2.18572459e+00,  3.14447104e+00,
        9.97933889e-01, -1.37911607e-02,  3.57438619e-01,  2.99542121e+00,
        3.80608737e-01,  3.57624940e+00,  4.28828446e-01,  9.19133166e-01,
        1.65869075e+00, -8.95373236e-02,  2.05965378e+00,  2.74007782e+00,
        9.30610490e-01,  2.89536131e+00,  1.92435640e+00,  1.97326158e+00,
        7.25432572e-01,  2.10823344e+00, -8.86384151e-02,  3.41109448e-02,
       -1.07110431e-01,  9.27803264e-01,  2.59504815e+00,  1.80304586e+00,
        3.44435435e-01,  5.02356025e-01, -6.88810243e-01,  2.87951101e+00,
        1.66033385e+00,  3.40990794e-01,  2.19693795e+00,  3.05898719e+00,
        6.98310209e-01,  2.25394549e+00,  2.27920203e+00,  1.82492649e+00,
        3.24725763e+00,  1.07562911e+00,  3.03032080e+00,  3.31808282e+00,
        1.60747052e+00,  2.02138436e+00,  2.29299902e+00,  2.83238978e+00,
        2.84661842e+00,  3.91477011e-01,  3.28505025e+00,  5.83469674e-01,
        2.73747986e+00,  1.23088361e+00,  2.68812460e+00,  1.24502076e+00,
        2.55250406e+00,  2.66206520e+00,  1.08487563e-01,  1.29842802e+00,
        6.07460597e-01,  2.82932734e+00,  9.50594839e-01,  2.77646488e+00,
        1.56748173e+00,  3.02110068e+00,  1.00693274e-01,  9.65975476e-02,
        3.81176433e-01,  4.49071750e-01,  1.85581301e+00,  9.47302199e-02,
        3.40269183e-01,  1.70689468e+00,  1.55816763e+00,  7.67084293e-01,
        1.79385050e+00,  2.16657676e+00,  1.97113532e+00, -2.29484935e-01,
        1.12352762e+00,  2.57068370e-01,  1.05438771e-01,  2.93374643e+00,
        2.28326331e+00,  4.44161416e-01,  2.91260660e+00,  1.10366750e+00,
        1.77454006e+00,  1.83791030e+00,  1.08289503e+00,  1.82097242e+00,
        3.23251899e+00,  9.45729621e-01,  8.68114193e-01,  2.15985735e+00,
        1.89018164e+00,  1.05480379e+00,  2.07137530e+00, -8.47039923e-01,
        8.34057315e-01,  7.93413806e-01,  1.00919004e-01,  2.67045288e+00,
        1.65473070e+00,  6.22306817e-01,  1.10671400e-02,  1.28291221e+00,
       -7.10339988e-02, -3.24513993e-02,  9.99345535e-01,  9.21796043e-01,
       -3.14683640e-01,  5.05726846e-01,  3.01735679e-01,  2.12690466e+00,
        1.87792415e+00,  3.41064738e+00,  1.64919691e+00,  3.21856111e+00,
       -1.57536087e-01,  2.77341799e+00,  5.05754730e-01,  2.75033019e+00,
        3.53826818e-01,  1.27380885e+00,  8.00940382e-01,  6.31535169e-01,
        1.60078426e+00, -5.19881739e-02,  2.74735615e+00,  2.12544919e+00,
        3.00295323e+00,  2.70103284e+00,  8.88041240e-01,  2.90782631e+00,
        1.41030878e+00,  2.59644328e+00,  1.34252157e+00,  2.59661478e+00,
        1.96555197e+00,  5.21949969e-01,  1.46858701e+00,  1.60470843e+00,
        1.39965652e+00,  1.26781363e+00, -2.12735425e-01, -1.09071087e-01,
        3.99095786e-01,  1.16833564e+00,  1.97276558e+00,  8.65442575e-01,
        4.53079154e-01,  2.62294808e+00,  1.93975182e+00,  4.71633964e-01,
        2.10134208e+00,  2.26037305e+00, -5.63384250e-01,  6.31610607e-02,
        2.42694144e+00,  1.00248009e+00,  1.47264858e+00,  2.24919787e-01,
        2.42186541e+00,  2.32854463e+00,  2.74179404e+00,  1.69366590e-01,
        2.67059986e+00,  5.46781147e-01,  1.96228779e+00,  3.03977856e+00,
        2.39320512e+00,  2.75808950e+00,  3.55758004e-01,  1.80988631e+00,
       -2.09102022e-01,  1.60668249e+00,  2.45746275e+00,  1.65943463e-01,
        1.29744026e+00,  1.43852074e+00,  3.96386352e-01, -2.52605167e-02,
        1.16973003e+00,  1.38927334e+00,  1.24300647e+00,  2.68133894e+00,
        3.16341904e+00,  2.63665479e+00,  1.73749060e+00,  2.80307268e+00,
        1.28782923e+00,  1.59278756e+00,  1.84484360e+00,  2.43758776e+00,
        2.83893372e+00,  3.27167766e+00,  1.61261885e+00,  5.99649875e-01,
        2.16554713e+00,  1.40259656e+00,  1.85917819e+00,  2.14740453e+00,
        8.64446816e-01,  1.93688214e-02,  1.90490794e+00,  2.16087527e+00,
        2.76973180e-01,  5.25505047e-01,  3.48684910e-01,  3.31396386e+00,
        1.12617151e+00,  3.86276618e-01,  2.19399846e+00,  1.91754402e+00,
        1.90877369e+00,  4.05088890e-01,  3.28017049e+00,  5.83603276e-01,
        1.83622310e+00,  2.06235014e+00,  5.79582292e-01,  3.03818548e+00,
       -2.76755486e-01,  2.25402476e+00,  3.23461528e+00,  4.32463422e-01,
        1.37549281e+00,  1.13451617e+00,  2.82483937e+00,  2.75198999e+00,
        1.38659704e+00,  1.00799751e+00,  1.52793614e+00,  2.82841381e+00,
        2.14650928e+00, -1.01056411e-03,  2.29270658e+00,  6.90135660e-01,
        2.39317190e+00, -2.91459900e-01,  3.06207766e+00,  3.42954889e+00,
        1.16122846e+00,  2.24111987e+00,  2.21584934e+00,  1.85022840e+00,
        2.93540950e+00, -4.43741912e-01,  8.45850010e-01,  1.89982712e+00,
        2.96089820e+00,  8.99492099e-01,  3.45785470e+00,  2.26421602e+00,
        2.77447565e+00,  1.00181975e+00,  5.95112059e-01,  6.09614110e-01,
        3.77059656e-01,  2.93768201e+00,  1.31911215e+00,  7.57323566e-02,
        3.01639784e+00,  1.85760685e+00,  3.36033602e+00,  2.16558877e+00,
        4.92994264e-01,  2.49913790e+00,  2.71302930e+00,  2.75382134e+00,
        2.15873148e+00,  2.73426937e+00,  2.85209351e+00,  8.34797802e-01,
        1.58998890e+00,  5.67052911e-01,  2.00342783e+00,  2.40312833e+00,
        2.84841065e+00,  6.98044955e-01,  2.59413945e-01,  7.90410171e-01,
        8.79665738e-01,  1.63117873e+00,  1.98233703e+00,  1.49022526e+00,
        3.74343328e-01,  1.80362829e-01,  2.18112489e+00,  1.85702040e+00,
        3.68344607e+00,  1.58800489e+00, -2.25416686e-01,  1.95971445e+00,
        8.23085122e-01,  2.81122410e+00,  2.61289308e+00,  4.02020426e-01,
        1.09511042e+00,  2.98079693e+00,  5.60065848e-01,  1.90885711e+00,
        7.90610575e-01,  6.77521256e-01,  1.51382782e-01,  2.51802802e-01,
        2.07215766e+00,  9.91876092e-01,  3.43548090e-02,  8.81620930e-01,
        1.22953475e+00,  1.71884398e+00,  1.62863530e+00,  2.05871681e-02,
        1.94853579e+00,  2.28250037e+00,  9.39177522e-01, -6.11229545e-01,
        3.00859920e+00,  3.14671740e-01,  1.65282085e-01,  3.13314457e+00,
        1.99290203e+00, -1.94997923e-01,  1.49536887e-01,  5.67290899e-01,
        3.27045797e-01, -1.38953646e-02,  2.72338890e+00, -3.59974073e-01,
        2.68157527e+00,  6.65071188e-01,  2.98210063e+00,  1.56405062e+00,
        1.18489032e+00,  3.10891418e+00,  2.50470528e+00,  8.40838130e-02,
        1.44739050e+00,  5.74468929e-01,  2.78889319e+00,  1.71667836e+00,
        2.33915787e+00,  1.68170795e+00,  5.69159894e-01,  2.64321560e+00,
       -1.34104082e-01,  1.79827622e+00,  4.05075797e-01,  2.18560546e+00,
        2.69476656e-01,  5.64033676e-01,  9.17615540e-01,  9.56405086e-01,
        1.04800898e+00,  2.04998717e+00,  1.34053115e+00,  2.58009650e+00,
        6.88144001e-01,  3.33229584e+00,  1.83765671e+00,  1.93791059e+00,
        1.08005631e+00,  3.14591527e+00,  2.07114833e+00, -5.98574928e-03,
        1.43945371e+00,  2.13652462e+00, -3.71272396e-01,  2.47899852e+00,
        3.43705637e+00, -2.38937254e-01,  1.96259120e+00,  1.10015133e+00,
        1.17518273e+00,  2.15704049e+00, -2.18379096e-01,  2.72997267e+00,
        1.96804515e+00, -6.90824163e-01,  2.76252025e+00,  1.91289904e+00,
        3.08618076e+00,  2.89837439e-01, -6.01607507e-01,  3.09308010e+00,
        1.53924014e-01,  1.63335239e+00,  1.70540043e+00,  3.45386881e+00,
        1.99142058e+00,  1.78778218e+00,  1.67770819e+00,  2.25925501e+00,
        8.78485562e-01,  1.56220369e+00,  3.04828023e+00,  6.72421409e-02,
        7.83692728e-01,  4.94856661e-01,  1.44923124e+00,  2.19533810e+00,
        1.38693322e+00, -3.81482108e-01, -5.97407456e-02,  1.32251146e+00,
       -2.41736527e-02, -3.22475704e-01,  2.66013759e+00,  5.62575678e-01,
        8.73427338e-01,  1.60778661e+00, -2.81764681e-01,  5.97535826e-01,
        6.83240588e-01,  9.47945811e-01,  2.53155692e+00,  1.91898468e-01,
        3.24555976e+00,  2.11011598e+00,  3.77668829e+00, -2.66531564e-01,
        1.74679879e-01,  1.32913465e+00,  1.88959943e+00,  1.72085044e+00,
        1.27366135e+00, -3.07923592e-01,  1.13472720e+00,  1.54226143e+00,
       -2.67415161e-01,  1.14796712e+00,  1.37715592e+00, -2.36484172e-01,
        5.88076549e-01,  2.89517632e+00,  3.52824377e+00,  5.53414589e-01,
        2.56247711e+00,  9.77960350e-01,  1.54392631e+00,  3.01379761e+00,
       -6.65254009e-03,  1.00308255e+00,  3.38771720e-01,  1.55897748e+00,
        1.64583642e+00,  4.10944489e-01,  2.92744624e+00,  1.20324797e+00,
       -4.71576222e-01,  2.70580822e+00,  5.88907074e-01,  1.17312431e+00,
        3.69436767e-01,  2.44582801e+00,  3.22847730e+00,  2.69385575e+00,
        1.79480347e+00,  2.64000682e+00,  2.46640253e-01,  3.17172576e+00,
        1.95729840e+00, -5.89148220e-02,  5.59727971e-01,  4.09537850e-01,
        2.29528922e+00,  3.06360079e+00,  2.02110804e+00,  2.39754690e-01,
        1.62650801e+00,  1.35416367e+00,  2.38123773e+00,  4.78812982e-01,
       -2.66217294e-01,  2.37892571e+00,  2.12375542e+00,  5.47644375e-01,
        2.68411673e+00,  9.60595931e-01,  1.75249970e+00,  1.37284899e+00,
        1.20764250e+00,  1.40586473e+00,  2.79100625e+00,  1.12118922e+00,
        1.34292881e+00,  1.26419682e+00,  1.97259986e+00,  6.55264617e-01,
       -1.51622755e-01,  1.57219810e+00,  1.62305559e+00,  1.66904408e-01,
        2.17670612e+00, -4.88048954e-01,  2.11262880e-01,  5.34812595e-01,
        3.63841786e-01,  2.29982576e+00,  2.71173653e+00,  3.09450476e+00,
        3.20262979e+00,  2.28874689e-01,  1.01678855e+00,  1.76950928e+00,
        1.43697892e+00,  1.26787091e+00,  7.37434531e-02, -3.84022444e-01,
        2.14426025e+00,  1.19259188e+00,  2.49466205e-01,  1.93673525e+00,
        1.95413738e-01,  2.34606540e+00,  2.15310849e+00,  2.06793689e+00,
        1.33584788e+00,  1.89623508e+00,  1.45704307e-01,  1.66129410e+00,
        8.63035585e-01,  2.82487589e+00,  3.78634721e-03,  2.76714035e-01,
        2.94619591e+00,  1.61758934e+00,  2.78436900e+00, -2.84508011e-01,
        1.04057252e-01,  1.89202302e+00,  2.47178624e+00,  2.42250850e+00,
        7.44407266e-01,  2.31736479e+00,  2.26523762e+00,  1.13391581e+00,
       -1.52312512e-01, -4.08410559e-01,  2.30012409e+00,  2.91767093e+00,
        5.01507645e-01,  3.04104680e+00,  1.88890572e-01,  7.04034618e-02,
        4.74377868e-01,  1.84494360e+00,  1.76948953e+00,  7.54211171e-01,
        2.12235093e+00, -8.03784350e-02,  2.64669386e+00,  2.24502337e+00,
        9.66418899e-01,  1.82214315e+00,  2.71554428e+00,  2.93877913e+00,
       -1.59037308e-01,  1.40209890e+00,  1.13066929e+00,  1.82286306e+00,
        9.57156045e-01,  2.08960699e+00,  2.04446779e+00, -4.23388988e-01,
        1.14144221e+00,  3.00261055e+00,  1.07156591e+00,  1.20330581e+00,
        3.17161023e+00,  6.69271310e-01,  2.02786047e+00,  2.72127535e+00,
        1.57448094e+00,  1.18619384e+00,  8.72141317e-01,  1.47483858e+00,
        2.63228247e+00,  2.44183471e+00,  1.07277348e-01,  2.12922236e+00,
        2.58881896e+00, -3.37932631e-01,  1.81761503e+00,  2.78086326e+00,
        2.35611535e+00,  1.97898819e+00,  1.72422438e+00,  3.08932602e+00,
        1.84995315e+00,  2.63252772e-01,  1.04888229e+00,  2.00548093e+00,
        5.90728259e-01,  1.66447792e+00,  1.14848785e+00,  9.90359181e-01,
        1.60435901e+00,  2.36076817e+00,  1.79719320e+00,  1.30954428e+00,
        1.74098758e+00,  6.86157831e-01,  5.94995411e-01,  1.19477279e+00,
        3.13172232e+00,  9.51135718e-01, -2.22284004e-01,  1.27373400e+00,
        1.60828117e+00,  2.65445225e+00,  1.08607299e+00, -5.03979090e-02,
        1.26070649e-02,  2.46651299e+00,  2.01386915e+00,  1.99869788e+00,
        2.59387601e+00, -5.49409481e-01,  2.84526551e+00,  2.44791893e+00,
        1.83889475e+00,  1.12657515e+00,  2.95020734e+00,  4.18806518e-01,
        8.44331405e-01,  2.49159710e+00,  1.19326040e+00,  1.54274361e+00,
        7.13032971e-01,  1.37644190e+00,  2.46650780e+00,  2.25774599e+00,
       -1.20063309e-01,  2.78245042e+00,  3.98048291e-01,  2.01592866e+00,
        2.67892544e+00,  2.28482950e-01,  2.37578424e+00,  1.43376920e+00,
        2.49946227e+00,  2.40820815e+00,  1.25786442e+00,  4.28451397e-01,
        2.02495723e+00,  2.69212489e+00,  9.02830274e-01, -3.68469343e-01,
        1.63427959e+00,  9.37621685e-01,  1.95728623e+00,  1.18942692e+00,
        2.35315490e+00,  1.38776498e-01,  2.12864573e+00,  2.25167862e+00,
        3.05816952e-02,  2.10354852e+00,  3.03492627e+00,  2.09696027e+00,
        3.19608606e+00, -1.11311799e-01,  1.62992790e+00,  8.84643301e-01,
        7.19296317e-01,  1.89423742e+00,  2.07992504e+00,  2.68542340e+00,
        2.61622771e+00, -7.30386345e-01,  2.16790347e+00,  1.31191015e+00,
        2.04754374e+00,  1.27075264e+00,  2.82369513e+00,  6.37770080e-01,
        6.69668416e-01,  2.45445804e+00, -8.30126301e-02,  1.35149926e+00,
        8.14462097e-02, -4.44564767e-02,  4.03840483e+00,  2.40376177e+00,
        2.08267380e+00,  3.94220771e-01,  4.66765311e-01,  7.75612481e-04,
       -1.69506235e-01,  3.24575144e+00,  2.17449569e+00,  2.76459686e+00,
        2.50840481e+00, -5.50345313e-01, -2.45037321e-01,  1.65853414e+00,
        1.22171032e+00,  3.95998575e-01,  1.71611813e+00,  1.93645475e+00])

In [33]:
predict_data['price_range']=predicted_price

In [34]:
predict_data.head()

,battery_power,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,three_g,touch_screen,price_range
0,1043,1.8,1,14,0,5,0.1,3,16,226,1412,3476,12,7,0,1,2.568374
1,841,0.5,1,4,1,61,0.8,5,12,746,857,3895,6,0,1,0,2.920803
2,1807,2.8,0,1,0,27,0.9,3,4,1270,1366,2396,17,10,0,1,2.276365
3,1546,0.5,1,18,1,25,0.5,8,20,295,1752,3893,10,0,1,1,3.398329
4,1434,1.4,0,11,1,49,0.5,6,18,749,810,1773,15,8,1,0,1.206277

In [35]:
# converting 'price' from float to int 
predict_data['price_range'] = predict_data['price_range'].astype(int)

In [36]:
predict_data.head(10)

,battery_power,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,three_g,touch_screen,price_range
0,1043,1.8,1,14,0,5,0.1,3,16,226,1412,3476,12,7,0,1,2
1,841,0.5,1,4,1,61,0.8,5,12,746,857,3895,6,0,1,0,2
2,1807,2.8,0,1,0,27,0.9,3,4,1270,1366,2396,17,10,0,1,2
3,1546,0.5,1,18,1,25,0.5,8,20,295,1752,3893,10,0,1,1,3
4,1434,1.4,0,11,1,49,0.5,6,18,749,810,1773,15,8,1,0,1
5,1464,2.9,1,5,1,50,0.8,8,9,569,939,3506,10,7,1,1,2
6,1718,2.4,0,1,0,47,1.0,2,3,1283,1374,3873,14,2,0,0,3
7,833,2.4,1,0,0,62,0.8,1,2,1312,1880,1495,7,2,0,1,1
8,1111,2.9,1,9,1,25,0.6,5,19,556,876,3485,11,9,1,1,2
9,1520,0.5,0,1,0,25,0.5,3,20,52,1009,651,6,0,1,0,0